version: 1.6.2.{build}
branches:
  only:
  - feature/Feature-Fix.Build
configuration: Release
build:
  verbosity: minimal
artifacts:
- path: '\SpecExpress\src\SpecExpress\bin\Release\SpecExpress.dll'
deploy:
- provider: NuGet
  api_key:
    secure: aqBZt1UAKmddNzvrIH27l4bghli3+5teYmP1KMF+nnuah4+ZtGmFpxBqTwFzrsRF
assembly_info:
  patch: true
  file: \SpecExpress\src\SpecExpress\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
